[package]
name = "rust_book"
version = "0.1.0"
authors = ["ilya.ryabchuk@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rstest = "0.6.4"
